services:
  - type: web
    name: golf-tournament
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:socket_app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    buildFilter:
      paths:
        - frontend/**
        - app.py
        - requirements.txt
        - build.sh
