services:
  - type: web
    name: golf-tournament-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://gold-tawny.vercel.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Accept,Authorization
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Max-Age
        value: "3600"
    healthCheckPath: /health
    healthCheckTimeout: 5
    autoDeploy: true
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

databases:
  - name: golf-tournament-db
    databaseName: golf_tournament
    user: golf_tournament
    plan: free
