services:
  - type: web
    name: golf-tournament-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://gold-tawny.vercel.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Accept,Authorization
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Max-Age
        value: "3600"

databases:
  - name: golf-tournament-db
    databaseName: golf_tournament
    user: golf_tournament
    plan: free
