"""add group_order to participant

Revision ID: 8d153ed82ea8
Revises: aa80595ad2ea
Create Date: 2024-12-26 09:19:05.078847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d153ed82ea8'
down_revision = 'aa80595ad2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkins')
    op.drop_table('participants')
    op.drop_table('groups')
    op.drop_table('tournaments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('group_number', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('member_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('handicap', sa.FLOAT(), nullable=True),
    sa.Column('pre_group_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('check_in_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('check_in_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('participant_id', sa.INTEGER(), nullable=False),
    sa.Column('checkin_time', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
