"""Add group_code to Participant

Revision ID: aa80595ad2ea
Revises: 
Create Date: 2024-12-26 00:48:29.149071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa80595ad2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    op.drop_table('group')
    op.drop_table('tournament')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('group_number', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('member_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('handicap', sa.FLOAT(), nullable=True),
    sa.Column('pre_group_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('group_number', sa.VARCHAR(length=10), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('check_in_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('check_in_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
